// Decompiled with JetBrains decompiler
// Type: GooglePlayGames.Native.NativeQuestClient
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null

using GooglePlayGames.BasicApi.Quests;
using GooglePlayGames.Native.Cwrapper;
using GooglePlayGames.Native.PInvoke;
using GooglePlayGames.OurUtils;
using System;
using System.Collections.Generic;

namespace GooglePlayGames.Native
{
  internal class NativeQuestClient : IQuestsClient
  {
    private readonly GooglePlayGames.Native.PInvoke.QuestManager mManager;

    internal NativeQuestClient(GooglePlayGames.Native.PInvoke.QuestManager manager)
    {
      this.mManager = Misc.CheckNotNull<GooglePlayGames.Native.PInvoke.QuestManager>(manager);
    }

    public void Fetch(GooglePlayGames.BasicApi.DataSource source, string questId, Action<GooglePlayGames.BasicApi.ResponseStatus, IQuest> callback)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      NativeQuestClient.\u003CFetch\u003Ec__AnonStorey0 fetchCAnonStorey0 = new NativeQuestClient.\u003CFetch\u003Ec__AnonStorey0();
      // ISSUE: reference to a compiler-generated field
      fetchCAnonStorey0.callback = callback;
      Misc.CheckNotNull<string>(questId);
      // ISSUE: reference to a compiler-generated field
      Misc.CheckNotNull<Action<GooglePlayGames.BasicApi.ResponseStatus, IQuest>>(fetchCAnonStorey0.callback);
      // ISSUE: reference to a compiler-generated field
      // ISSUE: reference to a compiler-generated field
      fetchCAnonStorey0.callback = CallbackUtils.ToOnGameThread<GooglePlayGames.BasicApi.ResponseStatus, IQuest>(fetchCAnonStorey0.callback);
      // ISSUE: reference to a compiler-generated method
      this.mManager.Fetch(ConversionUtils.AsDataSource(source), questId, new Action<GooglePlayGames.Native.PInvoke.QuestManager.FetchResponse>(fetchCAnonStorey0.\u003C\u003Em__0));
    }

    public void FetchMatchingState(GooglePlayGames.BasicApi.DataSource source, QuestFetchFlags flags, Action<GooglePlayGames.BasicApi.ResponseStatus, List<IQuest>> callback)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      NativeQuestClient.\u003CFetchMatchingState\u003Ec__AnonStorey1 stateCAnonStorey1 = new NativeQuestClient.\u003CFetchMatchingState\u003Ec__AnonStorey1();
      // ISSUE: reference to a compiler-generated field
      stateCAnonStorey1.callback = callback;
      // ISSUE: reference to a compiler-generated field
      Misc.CheckNotNull<Action<GooglePlayGames.BasicApi.ResponseStatus, List<IQuest>>>(stateCAnonStorey1.callback);
      // ISSUE: reference to a compiler-generated field
      // ISSUE: reference to a compiler-generated field
      stateCAnonStorey1.callback = CallbackUtils.ToOnGameThread<GooglePlayGames.BasicApi.ResponseStatus, List<IQuest>>(stateCAnonStorey1.callback);
      // ISSUE: reference to a compiler-generated method
      this.mManager.FetchList(ConversionUtils.AsDataSource(source), (int) flags, new Action<GooglePlayGames.Native.PInvoke.QuestManager.FetchListResponse>(stateCAnonStorey1.\u003C\u003Em__0));
    }

    public void ShowAllQuestsUI(Action<QuestUiResult, IQuest, IQuestMilestone> callback)
    {
      Misc.CheckNotNull<Action<QuestUiResult, IQuest, IQuestMilestone>>(callback);
      callback = CallbackUtils.ToOnGameThread<QuestUiResult, IQuest, IQuestMilestone>(callback);
      this.mManager.ShowAllQuestUI(NativeQuestClient.FromQuestUICallback(callback));
    }

    public void ShowSpecificQuestUI(IQuest quest, Action<QuestUiResult, IQuest, IQuestMilestone> callback)
    {
      Misc.CheckNotNull<IQuest>(quest);
      Misc.CheckNotNull<Action<QuestUiResult, IQuest, IQuestMilestone>>(callback);
      callback = CallbackUtils.ToOnGameThread<QuestUiResult, IQuest, IQuestMilestone>(callback);
      NativeQuest quest1 = quest as NativeQuest;
      if (quest1 == null)
      {
        Logger.e("Encountered quest that was not generated by this IQuestClient");
        callback(QuestUiResult.BadInput, (IQuest) null, (IQuestMilestone) null);
      }
      else
        this.mManager.ShowQuestUI(quest1, NativeQuestClient.FromQuestUICallback(callback));
    }

    private static QuestUiResult UiErrorToQuestUiResult(CommonErrorStatus.UIStatus status)
    {
      switch (status + 6)
      {
        case ~(CommonErrorStatus.UIStatus.ERROR_INTERNAL | CommonErrorStatus.UIStatus.VALID):
          return QuestUiResult.UserCanceled;
        case CommonErrorStatus.UIStatus.VALID:
          return QuestUiResult.Timeout;
        case ~CommonErrorStatus.UIStatus.ERROR_NOT_AUTHORIZED:
          return QuestUiResult.VersionUpdateRequired;
        case ~CommonErrorStatus.UIStatus.ERROR_VERSION_UPDATE_REQUIRED:
          return QuestUiResult.NotAuthorized;
        case ~CommonErrorStatus.UIStatus.ERROR_TIMEOUT:
          return QuestUiResult.InternalError;
        default:
          if (status == CommonErrorStatus.UIStatus.ERROR_UI_BUSY)
            return QuestUiResult.UiBusy;
          Logger.e("Unknown error status: " + (object) status);
          return QuestUiResult.InternalError;
      }
    }

    private static Action<GooglePlayGames.Native.PInvoke.QuestManager.QuestUIResponse> FromQuestUICallback(Action<QuestUiResult, IQuest, IQuestMilestone> callback)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: reference to a compiler-generated method
      return new Action<GooglePlayGames.Native.PInvoke.QuestManager.QuestUIResponse>(new NativeQuestClient.\u003CFromQuestUICallback\u003Ec__AnonStorey2() { callback = callback }.\u003C\u003Em__0);
    }

    public void Accept(IQuest quest, Action<GooglePlayGames.BasicApi.Quests.QuestAcceptStatus, IQuest> callback)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      NativeQuestClient.\u003CAccept\u003Ec__AnonStorey3 acceptCAnonStorey3 = new NativeQuestClient.\u003CAccept\u003Ec__AnonStorey3();
      // ISSUE: reference to a compiler-generated field
      acceptCAnonStorey3.callback = callback;
      Misc.CheckNotNull<IQuest>(quest);
      // ISSUE: reference to a compiler-generated field
      Misc.CheckNotNull<Action<GooglePlayGames.BasicApi.Quests.QuestAcceptStatus, IQuest>>(acceptCAnonStorey3.callback);
      // ISSUE: reference to a compiler-generated field
      // ISSUE: reference to a compiler-generated field
      acceptCAnonStorey3.callback = CallbackUtils.ToOnGameThread<GooglePlayGames.BasicApi.Quests.QuestAcceptStatus, IQuest>(acceptCAnonStorey3.callback);
      NativeQuest quest1 = quest as NativeQuest;
      if (quest1 == null)
      {
        Logger.e("Encountered quest that was not generated by this IQuestClient");
        // ISSUE: reference to a compiler-generated field
        acceptCAnonStorey3.callback(GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.BadInput, (IQuest) null);
      }
      else
      {
        // ISSUE: reference to a compiler-generated method
        this.mManager.Accept(quest1, new Action<GooglePlayGames.Native.PInvoke.QuestManager.AcceptResponse>(acceptCAnonStorey3.\u003C\u003Em__0));
      }
    }

    private static GooglePlayGames.BasicApi.Quests.QuestAcceptStatus FromAcceptStatus(CommonErrorStatus.QuestAcceptStatus status)
    {
      switch (status + 5)
      {
        case ~(CommonErrorStatus.QuestAcceptStatus.ERROR_INTERNAL | CommonErrorStatus.QuestAcceptStatus.VALID):
          return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.Timeout;
        case ~CommonErrorStatus.QuestAcceptStatus.ERROR_NOT_AUTHORIZED:
          return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.NotAuthorized;
        case (CommonErrorStatus.QuestAcceptStatus) 3:
          return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.InternalError;
        case (CommonErrorStatus.QuestAcceptStatus) 6:
          return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.Success;
        default:
          if (status == CommonErrorStatus.QuestAcceptStatus.ERROR_QUEST_NOT_STARTED)
            return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.QuestNotStarted;
          if (status == CommonErrorStatus.QuestAcceptStatus.ERROR_QUEST_NO_LONGER_AVAILABLE)
            return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.QuestNoLongerAvailable;
          Logger.e("Encountered unknown status: " + (object) status);
          return GooglePlayGames.BasicApi.Quests.QuestAcceptStatus.InternalError;
      }
    }

    public void ClaimMilestone(IQuestMilestone milestone, Action<GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus, IQuest, IQuestMilestone> callback)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      NativeQuestClient.\u003CClaimMilestone\u003Ec__AnonStorey4 milestoneCAnonStorey4 = new NativeQuestClient.\u003CClaimMilestone\u003Ec__AnonStorey4();
      // ISSUE: reference to a compiler-generated field
      milestoneCAnonStorey4.callback = callback;
      Misc.CheckNotNull<IQuestMilestone>(milestone);
      // ISSUE: reference to a compiler-generated field
      Misc.CheckNotNull<Action<GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus, IQuest, IQuestMilestone>>(milestoneCAnonStorey4.callback);
      // ISSUE: reference to a compiler-generated field
      // ISSUE: reference to a compiler-generated field
      milestoneCAnonStorey4.callback = CallbackUtils.ToOnGameThread<GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus, IQuest, IQuestMilestone>(milestoneCAnonStorey4.callback);
      NativeQuestMilestone milestone1 = milestone as NativeQuestMilestone;
      if (milestone1 == null)
      {
        Logger.e("Encountered milestone that was not generated by this IQuestClient");
        // ISSUE: reference to a compiler-generated field
        milestoneCAnonStorey4.callback(GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.BadInput, (IQuest) null, (IQuestMilestone) null);
      }
      else
      {
        // ISSUE: reference to a compiler-generated method
        this.mManager.ClaimMilestone(milestone1, new Action<GooglePlayGames.Native.PInvoke.QuestManager.ClaimMilestoneResponse>(milestoneCAnonStorey4.\u003C\u003Em__0));
      }
    }

    private static GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus FromClaimStatus(CommonErrorStatus.QuestClaimMilestoneStatus status)
    {
      switch (status + 5)
      {
        case ~(CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_INTERNAL | CommonErrorStatus.QuestClaimMilestoneStatus.VALID):
          return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.Timeout;
        case ~CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_NOT_AUTHORIZED:
          return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.NotAuthorized;
        case (CommonErrorStatus.QuestClaimMilestoneStatus) 3:
          return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.InternalError;
        case (CommonErrorStatus.QuestClaimMilestoneStatus) 6:
          return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.Success;
        default:
          if (status == CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_MILESTONE_CLAIM_FAILED)
            return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.MilestoneClaimFailed;
          if (status == CommonErrorStatus.QuestClaimMilestoneStatus.ERROR_MILESTONE_ALREADY_CLAIMED)
            return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.MilestoneAlreadyClaimed;
          Logger.e("Encountered unknown status: " + (object) status);
          return GooglePlayGames.BasicApi.Quests.QuestClaimMilestoneStatus.InternalError;
      }
    }
  }
}
