// Decompiled with JetBrains decompiler
// Type: CC.ModType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 15F75AAD-48E7-469E-B756-4D8C100CB626
// Assembly location: D:\Dropbox\apps\android\com.GameCoaster.ProtectDungeon\1.92.2\apk\assets\bin\Data\Managed\Assembly-CSharp.dll

namespace CC
{
  public enum ModType
  {
    eNone = -1,
    eAcc = 0,
    eDmg = 1,
    eReload = 2,
    eAmmo = 3,
    eAsp = 4,
    eCool = 5,
    eCri = 6,
    eVsA = 7,
    eVsM = 8,
    eBulSpd = 9,
    eHP = 10,
    eDef = 11,
    eEvade = 12,
    eRegen = 13,
    eExp = 14,
    eGold = 15,
    eSkill = 16,
    eSpecial = 17,
    eCriDmg = 18,
    eFireBall = 19,
    eFireLance = 20,
    eRicochet = 21,
    eSoulBomb = 22,
    eBigShot = 23,
    eAddShot = 24,
    eMultiShot = 25,
    eStrongKick = 26,
    eBigShotAll = 27,
    eAddArrow = 28,
    eWarRage = 29,
    eLastStrongKick = 30,
    eSlashAll = 31,
    eSoulBombParty = 32,
    eFireBallRange = 33,
    eFireLanceRange = 34,
    eAssasinArea = 35,
    eRicochetDouble = 36,
    eAllSkill = 37,
    eResearch = 38,
    eTripleSword = 39,
    eTripleSwordPlus = 40,
    eDimensionKick = 41,
    eSevenSword = 42,
    eBonePenetrate = 43,
    ePartySwift = 44,
    eRandomShot = 45,
    eLongRage = 46,
    eFireBallDmg = 47,
    eFireLanceDmg = 48,
    eCriAssasinate = 49,
    eJavelinAddShot = 50,
    eHarvestHeal = 51,
    eKickArea = 52,
    eSwordPenetrate = 53,
    eAddSubLaser = 54,
    eSuperLaserDur = 55,
    eAlwaysIce = 56,
    eBigSnowBall = 57,
    eStrongerSlash = 58,
    eLastBigSlash = 59,
    eSpecialDuration = 60,
    eFirstThunder = 61,
    eChainBombDmg = 62,
    eElementalBombDmg = 63,
    eMax = 64,
  }
}
