// Decompiled with JetBrains decompiler
// Type: CC.MutateType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 2EE8B15F-8D58-4BD6-8905-91665367FCCE
// Assembly location: C:\Users\Andrew\Downloads\base\assets\bin\Data\Managed\Assembly-CSharp.dll

namespace CC
{
  public enum MutateType
  {
    eNone = -1,
    eBerserk = 0,
    eRedMyst = 1,
    eLifeBloom = 2,
    eBarrier = 3,
    eBlock = 4,
    eStealth = 5,
    eTeleport = 6,
    eInhibitor = 7,
    eDivine = 8,
    eBombard = 9,
    eNoAmmo = 10,
    eShift = 11,
    eAbsorb = 12,
    eInvincible = 13,
    eHealer = 14,
    eTaunt = 15,
    eDash = 16,
    eDrain = 17,
    eGiant = 18,
    eRegen = 19,
    eReload = 20,
    eWaste = 21,
    eSpotlight = 22,
    eStrength = 23,
    eSwift = 24,
    eRageFarmer = 25,
    eSacrifice = 26,
    eGoliat = 27,
    eGodBless = 28,
    eHusk = 29,
    eReflection = 30,
    eLastChance = 31,
    eTanker = 32,
    eShadow = 33,
    ePunch = 34,
    eWeakPoint = 35,
    eFitness = 36,
    eGemini = 37,
    eDarkMyst = 38,
    eButton = 39,
    eGuardian = 40,
    eSanctuary = 41,
    eKnights = 42,
    eSplit = 43,
    eTimeLimit = 44,
    eSoloPlay = 45,
    eIronKnights = 46,
    eJustOne = 47,
    eSlow = 48,
    eHaste = 49,
    eMax = 50,
    eAntiMagic = 51,
    eStunBomb = 52,
    eDristram = 53,
    eQuizOX = 54,
    eHeatManage = 55,
    eCriDown = 56,
    ePrecision = 57,
    eNoMainPhysical = 58,
    eNoMainMagical = 59,
    eOnlyCri = 60,
  }
}
