// Decompiled with JetBrains decompiler
// Type: CC.ResearchID
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 15F75AAD-48E7-469E-B756-4D8C100CB626
// Assembly location: D:\Dropbox\apps\android\com.GameCoaster.ProtectDungeon\1.92.2\apk\assets\bin\Data\Managed\Assembly-CSharp.dll

namespace CC
{
  public enum ResearchID
  {
    eNone,
    eArchitect,
    eSupply,
    eMiniBank,
    eMine,
    eGuild,
    eEducation,
    eCalculator,
    eHospital,
    eForge,
    eArmor,
    eMagic,
    eGuildBank,
    eMall,
    eVaccine,
    eAnvil,
    eScope,
    eHugeStatue,
    eFlag,
    eHardened,
    eTraining,
    eStone,
    eSocket,
    eMeditate,
    eRelic,
    eAcientPower,
    eAcientCall,
    eAcientWall,
    eAcientBlood,
    eAddShot,
    eMultiShot,
    eFireBall,
    eFireLance,
    eRicochet,
    eBigShot,
    eSoulBomb,
    eConsecration,
    eMoreKick,
    eMoreSword,
    eBattleExp,
    eSteel,
    eEmpower,
    eBattleTraining,
    eMecenaryTraining,
    eStockMarket,
    eAuction,
    eAcientStatue,
    eLegendary,
    eAwaken,
    eModifySum,
    eBasicLaser,
    eFrostBall,
    eHexaSlash,
    eThunder,
    eElementalShot,
    eAwakenSkill,
    eElementalExp,
    eUnlimitedPower,
    eUnlimitedShield,
    eMax,
  }
}
